service: synonym-service

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  timeout: 10
  memorySize: 1024
  
package:
  artifact: build/distributions/synonym-service.zip

functions:
  word-synonym:
    handler: pl.grizwold.synonym_service.handlers.WordHandler
    events:
      - http:
          path: word
          method: post
  sentence:
    handler: pl.grizwold.synonym_service.handlers.SentenceHandler
    events:
      - http:
          path: sentence
          method: post
